### ISSUE TITLE
Error script broken since commit 721f9cfc31a9b64bc2c07d9f0f76a7ead80783b5 on Python 3.10.3

### ISSUE THREAD

**Issue by Rugikex** [abrignoni/iLEAPP#1676]
The script no longer executes correctly following recent changes. After checking the history, the issue was introduced precisely in the following commit: 721f9cfc31a9b64bc2c07d9f0f76a7ead80783b5

I'm using Python 3.10.3

```bash
py .\ileappGUI.py
```

```bash
Traceback (most recent call last):
  File "XXX\iLEAPP\ileappGUI.py", line 6, in <module>
    import ileapp
  File "XXX\iLEAPP\ileapp.py", line 10, in <module>
    import scripts.report as report
  File "XXX\iLEAPP\scripts\report.py", line 17, in <module>
    from scripts.ilapfuncs import logfunc
  File "XXX\iLEAPP\scripts\ilapfuncs.py", line 17, in <module>
    from datetime import datetime, timezone, timedelta, UTC
ImportError: cannot import name 'UTC' from 'datetime' (XXX\Python\Python310\lib\datetime.py)
```

**Comment by abrignoni** [comment]
Update your python and try again please.

**Comment by Rugikex** [comment]
I thought my current Python version was compliant with the project's requirements.
The previous `README.md` stated that Python versions from 3.10 to 3.12 were supported, but that mention has since been removed.

What is the best current Python version to use for the project?

**Comment by Johann-PLW** [comment]
datetime.utc was added with Python3.11.

So as Alexis said, try to update your Python to 3.11 or 3.12, but don't try to use 3.13 or later.
It should be work after that.

**Comment by Johann-PLW** [comment]
We need to update the README.md file.

The best Python version to use for all LEAPP apps  is 3.12.x.

**Comment by Rugikex** [comment]
I switched to Python 3.12.10 and everything is working perfectly fine now on Windows. Thanks for the help!

**Comment by abrignoni** [comment]
Fixed in #1677 — `datetime.UTC` is 3.11+, so I switched it to `timezone.utc`. Thanks for reporting and pinpointing the exact commit, that made it a quick fix! I patched the same thing in RLEAPP (#350) and VLEAPP (#87) too. 3.10 works again. 🙏
