### ISSUE TITLE
Program failed parse and died, instead of skip over + continue with next item

### ISSUE THREAD

**Issue by evandrix** [abrignoni/iLEAPP#43]
- ran on Python 3.8.2 on macOS 10.15.4
- iLEAPP commit d53c9fbd8b57f0ad72361682e96605cabd991a61
- image from https://champdfa-ccsc-sp20.ctfd.io
  - direct download https://drive.google.com/file/d/1-Uy4RZIGsLzlulir4fLxTNG7IeoDiCvh

```
$ python ileapp.py /path/to/image
Procesing started. Please wait. This may take a few minutes...
--------------------------------------------------------------------------------------
iLEAPP: iOS Logs, Events, and Preferences Parser
Objective: Triage iOS Full System Extractions.
By: Agam Dua | @loopbackdev | loopback.dev
By: Alexis Brignoni | @AlexisBrignoni | abrignoni.com
Artifact categories to parse: 41
File/Directory selected: /path/to/image
--------------------------------------------------------------------------------------
Mobile Installation Logs function executing
Logs processed: 1
Lines processed: 595
Total apps: 133
Total installed apps: 123
Total uninstalled apps: 10
Total historical app reports: 133
Total system state events: 2
Mobile Installation Logs function completed.
Iconstate function executing
Screens: 2
Icons in bottom bar: 4
Iconstate function completed.
Webclips function executing
Webclips found: 1
Webclips function completed
Lastbuild function executing
iOS version is: 9.3.5
Lastbuild function completed.
iOSNotifications 11 function executing
Total notification directories processed:0
Total exported bplists from notifications:0
No notifications located.
iOS 11 Notifications function completed.
No files found for iOSNotifications12 -> *private/var/mobile/Library/UserNotifications/.
Cellular Wireless files function executing
Cellular Wireless files function completed
Incepted bplist extractions in KnowledgeC.db executing
Unsupported version9.3.5
ApplicationState.db queries executing
Installed app GUIDs and app locations processed: 42
ApplicationState.db queries completed.
Connected devices function executing
Data being interpreted for FRPD is of type: <class 'bytes'>
Found magic bytes in iTunes Prefs FRPD... Finding Usernames and Desktop names now
test - DESKTOP-T00FUVO
test - DESKTOP-T00FUVO
test - DESKTOP-T00FUVO
Connected devices function completed.
Traceback (most recent call last):
  File "ileapp.py", line 37, in <module>
    extract_and_process(image_fpath, extracttype, tosearch, log)
  File "/iLEAPP/extraction.py", line 113, in extract_and_process
    process_file_found(filefound, key, val, log, gui_window)
  File "/iLEAPP/extraction.py", line 169, in process_file_found
    globals()[key](filefound)
  File "/iLEAPP/contrib/call_history/main.py", line 12, in calhist
    cursor.execute(
sqlite3.OperationalError: no such column: ZSERVICE_PROVIDER
```

**Comment by evandrix** [comment]
- PySimpleGUI v4.18.2

additionally, GUI fails to open, and dies with the following error:

```
$ python ileappGUI.py
Exception ignored in: <function Output.__del__ at 0x10bd965e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2695, in __del__
AttributeError: 'NoneType' object has no attribute '__del__'
```

**Comment by abrignoni** [comment]
I am 100% sure what the problem is. What I am doing is moving all the
artifacts to the more robust ALEAPP codebase that does proper error
handling.
You can try the new version of iLEAPP here:
https://github.com/abrignoni/iLEAPP/tree/iLEAPP-1.2

It doesn't have all the artifacts the current master version of iLEAPP has
but I am porting them over daily. I hope to make this branch of ileapp the
new master version by next weekend. The reporting is nicer, clearner and it
even has a search feature per artifact.

**Comment by abrignoni** [comment]
Just ran the image in iLEAPP 1.2 GUI version and it generated the report with no problems. Will look at some of the  artifact errors moving forward. Sample images are great cause it helps with letting me know I need to add support for a specific iOS version/artifact. Thanks for testing. Let me know how working with iLEAPP 1.2 goes.

**Comment by evandrix** [comment]
yeah, in order to just continue with the CTF questions, i wrapped that line as such:

```
try: globals()[key](filefound)
except sqlite3.OperationalError as ex: pass
```

and the original branch program ran to completion, although, perhaps because it's old (v9.3.5) many of the results weren't sufficient to answer the CTF questions :(

**Comment by evandrix** [comment]
just checked out the iLEAPP-1.2 branch, GUI opens for me now, but look at the title 🤣 
<img width="792" src="https://user-images.githubusercontent.com/169669/80924152-fa897500-8db9-11ea-8a2e-eb898a8af3fb.png">

**Comment by abrignoni** [comment]
Yes. Currently, yesterday, added the ability for artifact scripts to
determine the version of iOS they are parsing. This will allow multiple
queries per artifact selecting the proper query to execute per the ios
version value. Sadly that takes a long time to implement alone. Working on
it.

**Comment by evandrix** [comment]
Yep, no worries, thank you very much for your awesome work on this tool!

**Comment by abrignoni** [comment]
LOLOLOLOLOL!!!

Fixed.

**Comment by abrignoni** [comment]
Thank you for testing and using. It will get better and better with time.
More and more artifacts from different ios versions. That is the plan. 👍

**Comment by evandrix** [comment]
sounds like a great plan ^_^

**Comment by abrignoni** [comment]
Adding some ios 9 artifacts now to the new ileapp. Run again late tonight
or tomorrow morning. Maybe the new stuff will help.

**Comment by evandrix** [comment]
Wow sure, ok

As a reference, these are the sort of questions I'm looking to answer:

* What mm/dd/yyyy did Nest connect?
* When was the last time this device was 100% charged? (mm/dd/yyyy hh:mm:ssAM/PM)
* What is the title of the webpage that was viewed the most?
* What is the name of the skin/color-scheme used for the game emulator? This should be a filename
* How long did the News App run in the background?
* What was the first app download from the appstore?
* What was the most recent emulator game obtained?
* How many applications were installed from the app store?
* What language is the user trying to learn?
* The user was reading a book in real life, but used their Fruit Pad to record the page that they had left off on. What number was it?
* Name one of the apps that were on this device's dock. Provide them in bundle format: com.provider.appname
* A reminder was made to get something, what was it?

**Comment by abrignoni** [comment]
Parse with new ILEAPP now. You will find some answers. Others (like the
browser stuff) I will port tomorrow. Spent my day researching and
implementing all the health database artifacts. They are a bunch!

**Comment by evandrix** [comment]
wah, are you never asleep? (like me) ahaha
