### ISSUE TITLE
Building wheel for astc_decomp_faster (pyproject.toml) error

### ISSUE THREAD

**Issue by daybreak2253** [abrignoni/iLEAPP#1114]
Hi, I'm trying to install but I get the following error. I'm running python 3.13.2.

```
Building wheels for collected packages: astc_decomp_faster
  Building wheel for astc_decomp_faster (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for astc_decomp_faster (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      C:\Users\Daybreak2253\AppData\Local\Temp\pip-build-env-9lf5kemr\overlay\Lib\site-packages\setuptools\dist.py:599: SetuptoolsDeprecationWarning: Invalid dash-separated key 'description-file' in 'metadata' (setup.cfg), please use the underscore name 'description_file' instead.
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2026-Mar-03, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self._enforce_underscore(opt, section)
      C:\Users\Daybreak2253\AppData\Local\Temp\pip-build-env-9lf5kemr\overlay\Lib\site-packages\setuptools\dist.py:599: SetuptoolsDeprecationWarning: Invalid dash-separated key 'long-description' in 'metadata' (setup.cfg), please use the underscore name 'long_description' instead.
      !!

              ********************************************************************************
              Usage of dash-separated 'long-description' will not be supported in future
              versions. Please use the underscore name 'long_description' instead.

              By 2026-Mar-03, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self._enforce_underscore(opt, section)
      C:\Users\Daybreak2253\AppData\Local\Temp\pip-build-env-9lf5kemr\overlay\Lib\site-packages\setuptools\dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: zlib/libpng License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      running bdist_wheel
      running build
      running build_ext
      building 'astc_decomp_faster' extension
      creating build\temp.win-amd64-cpython-313\Release\astc_dec
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iastc_dec -IC:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include -IC:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpastc_dec/astc_decomp.cpp /Fobuild\temp.win-amd64-cpython-313\Release\astc_dec\astc_decomp.obj
      astc_decomp.cpp
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iastc_dec -IC:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include -IC:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpastc_decomp.cpp /Fobuild\temp.win-amd64-cpython-313\Release\astc_decomp.obj
      astc_decomp.cpp
      astc_decomp.cpp(1300): warning C4996: 'Py_UNICODE': deprecated in 3.13
      astc_decomp.cpp(1302): warning C4996: 'Py_UNICODE': deprecated in 3.13
      astc_decomp.cpp(18397): warning C4018: '<': signed/unsigned mismatch
      astc_decomp.cpp(18482): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
      astc_decomp.cpp(18491): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
      astc_decomp.cpp(21288): error C3861: '_PyDict_SetItem_KnownHash': identifier not found
      astc_decomp.cpp(21297): error C3861: '_PyDict_SetItem_KnownHash': identifier not found
      astc_decomp.cpp(21308): error C3861: '_PyDict_SetItem_KnownHash': identifier not found
      astc_decomp.cpp(24067): warning C4244: '=': conversion from 'Py_ssize_t' to 'long', possible loss of data
      astc_decomp.cpp(24527): warning C4551: function call missing argument list
      astc_decomp.cpp(27897): error C2660: '_PyLong_AsByteArray': function does not take 5 arguments
      C:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include\cpython/longobject.h(111): note: see declaration of '_PyLong_AsByteArray'
      astc_decomp.cpp(27897): note: while trying to match the argument list '(PyLongObject *, unsigned char *, size_t, int, bool)'
      astc_decomp.cpp(28294): error C2660: '_PyLong_AsByteArray': function does not take 5 arguments
      C:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include\cpython/longobject.h(111): note: see declaration of '_PyLong_AsByteArray'
      astc_decomp.cpp(28294): note: while trying to match the argument list '(PyLongObject *, unsigned char *, size_t, int, bool)'
      astc_decomp.cpp(28567): error C2660: '_PyLong_AsByteArray': function does not take 5 arguments
      C:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include\cpython/longobject.h(111): note: see declaration of '_PyLong_AsByteArray'
      astc_decomp.cpp(28567): note: while trying to match the argument list '(PyLongObject *, unsigned char *, size_t, int, bool)'
      astc_decomp.cpp(28902): error C2660: '_PyLong_AsByteArray': function does not take 5 arguments
      C:\Users\Daybreak2253\AppData\Local\Programs\Python\Python313\include\cpython/longobject.h(111): note: see declaration of '_PyLong_AsByteArray'
      astc_decomp.cpp(28902): note: while trying to match the argument list '(PyLongObject *, unsigned char *, size_t, int, bool)'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for astc_decomp_faster
Failed to build astc_decomp_faster
ERROR: Failed to build installable wheels for some pyproject.toml based projects (astc_decomp_faster)
```

Can anyone help? I'm a real novice when it comes to python and GitHub!

**Comment by Johann-PLW** [comment]
Hi @daybreak2253,

As mentioned in the Requirements section in README, iLEAPP only works with Python from versions 3.10 to 3.12.
At the moment, the astc_decomp_faster library is failing to compile and install on Windows computers when using Python 3.13

So you have to use a supported version of Python. If you need Python 3.13, you can install a lower version and create a virtual environment to execute iLEAPP.
You need to locate the executable of Python 3.10, 3.11 or 3.12 and use it to create your virtual environment.
In a command prompt window, go to the iLEAPP directory and type the following commands:
 - C:\<*Python3.12_installation_path*>\python.exe -m venv .venv    (.venv is the name of the directory where all the dependencies will be installed)
 - .venv\Script\activate    (activation of the virtual environment)
 - python -m pip install pip --upgrade   (to update the Python installation package module)
 - pip install -r requirements.txt   (Install all dependencies for iLEAPP corresponding to the Python version used to create the virtual environment).


But you can also use [iLEAPP binaries](https://github.com/abrignoni/iLEAPP/releases): no Python installation needed 

Hope it will help.
